site_url: https://spectacular-crostata-851cec.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Project Category',
          name: 'category',
          widget: 'select',
          default: 'animals',
          options: [{ label: 'Animals', value: 'animals' }, { label: 'Food', value: 'food' }],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  - name: 'CareerVerseworldsList'
    label: 'CvWorlds'
    label_singular: 'World'
    folder: 'content/World'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'worldName', name: 'worldName', widget: 'string', required: true }
      - { label: 'world image', name: 'cover', widget: 'image', required: false, allow_multiple: false }

  - name: 'CVWorldTabs'
    label: 'CVWorldTabs'
    label_singular: 'World'
    folder: 'content/Worldt'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'wt/{{slug}}'
    fields:
      [ 
        { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false },
        { label: "Assigned World", name: "author",widget: "relation", collection: "CareerVerseworldsList",
          search_fields: ['worldName'],
          value_field: "{{slug}}",
          display_fields: ["{{worldName}}"],
        },
        {
          label: "Tab1",
          name: "profile",
          widget: "object",
          summary: '{{fields.name}}: {{fields.birthdate}}',
          fields:
          [
                { label: "Public",
                    name: "public",
                    widget: "boolean",
                    default: true
                },
                {label: "Name", name: "name", widget: "string"},
                { label: "Birthdate",
                    name: "birthdate",
                    widget: "date",
                    default: "",
                    format: "MM/DD/YYYY"
                },
                  {label: "Address",
                    name: "address",
                    widget: "object",
                    collapsed: true,
                    fields: [
                      {label: "Street Address", name: "street", widget: "string"},
                      {label: "City", name: "city", widget: "string"},
                      {label: "Postal Code", name: "post-code", widget: "string"}
                    ]
                  }
          ]
        },
        {
          label: "Tab2",
          name: "tab2",
          widget: "object",
          summary: '{{fields.name}}: {{fields.birthdate}}',
          fields:
          [
                { label: "Public",
                    name: "public",
                    widget: "boolean",
                    default: true
                },
                {label: "Name", name: "name", widget: "string"},
                { label: "Birthdate",
                    name: "birthdate",
                    widget: "date",
                    default: "",
                    format: "MM/DD/YYYY"
                },
                  {label: "Address",
                    name: "address",
                    widget: "object",
                    collapsed: true,
                    fields: [
                      {label: "Street Address", name: "street", widget: "string"},
                      {label: "City", name: "city", widget: "string"},
                      {label: "Postal Code", name: "post-code", widget: "string"}
                    ]
                  }
          ]
        },
        {
          label: "Tab3",
          name: "tab3",
          widget: "object",
          summary: '{{fields.name}}: {{fields.birthdate}}',
          fields:
          [
                { label: "Public",
                    name: "public",
                    widget: "boolean",
                    default: true
                },
                {label: "Name", name: "name", widget: "string"},
                { label: "Birthdate",
                    name: "birthdate",
                    widget: "date",
                    default: "",
                    format: "MM/DD/YYYY"
                },
                  {label: "Address",
                    name: "address",
                    widget: "object",
                    collapsed: true,
                    fields: [
                      {label: "Street Address", name: "street", widget: "string"},
                      {label: "City", name: "city", widget: "string"},
                      {label: "Postal Code", name: "post-code", widget: "string"}
                    ]
                  }
          ]
        },
        {
          label: "Tab4",
          name: "tab4",
          widget: "object",
          summary: '{{fields.name}}: {{fields.birthdate}}',
          fields:
          [
                { label: "Public",
                    name: "public",
                    widget: "boolean",
                    default: true
                },
                {label: "Name", name: "name", widget: "string"},
                { label: "Birthdate",
                    name: "birthdate",
                    widget: "date",
                    default: "",
                    format: "MM/DD/YYYY"
                },
                  {label: "Address",
                    name: "address",
                    widget: "object",
                    collapsed: true,
                    fields: [
                      {label: "Street Address", name: "street", widget: "string"},
                      {label: "City", name: "city", widget: "string"},
                      {label: "Postal Code", name: "post-code", widget: "string"}
                    ]
                  }
          ]
        }
      ]  
           
